version: '3'
services:      
  app:
    build: .
    ports:
     - "8090:8090"
    container_name: app
    environment:
      - NODE_ENV=production
    links: 
      - redis:redis
      - mongo:mongo
    depends_on: 
      - redis
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - ~/data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    container_name: redis